version: '2'
services:
  vault-dev:
    image: vault
    container_name: vault-dev
    ports:
      - "127.0.0.1:8201:1234"
    volumes:
      - ../vault-volume/file:/vault/file:rw
      - ../vault-volume/config:/vault/config:rw
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=devroot
    entrypoint: vault server -dev  -config=/vault/config/
