/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'victoryw' at '5/15/17 11:49 PM' with Gradle 3.2.1
 *
 * @author victoryw, @date 5/15/17 11:49 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
